services:

  postgres:
    image: pgvector/pgvector:pg18
    container_name: xnews-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: xnews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "15432:5432"

    volumes:
      - xnews_postgres_data:/var/lib/postgresql

volumes:
  xnews_postgres_data: