spring.application.name=X News
spring.datasource.url=jdbc:postgresql://localhost:5432/X-NEWS
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8080

jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_FOR_DEVELOPMENT_ONLY

