-- X-NEWS V4 roadmap step 7: links between events of one storyline. A
-- nightly job links events that share distinctive entities and are close in
-- meaning; from_event_id is the event that started first. followed_by means
-- the first ended before the second began (1st ODI -> 2nd ODI); related
-- means they overlapped in time. Additive only.

CREATE TABLE event_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_event_id bigint NOT NULL REFERENCES news_events (id),
    to_event_id bigint NOT NULL REFERENCES news_events (id),
    -- related | followed_by
    relation varchar(20) NOT NULL,
    -- centroid cosine similarity of the two events
    score double precision NOT NULL,
    -- distinctive entities both events mention
    shared_entities integer NOT NULL,
    run_id bigint REFERENCES extraction_runs (id),
    updated_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_event_relations_pair UNIQUE (from_event_id, to_event_id),
    CONSTRAINT ck_event_relations_not_self CHECK (from_event_id <> to_event_id)
);

CREATE INDEX idx_event_relations_to_event_id ON event_relations (to_event_id);
