-- X-NEWS V4 roadmap step 6: numeric claims as data. A claim is one
-- article's statement of a number about a subject ("Virat Kohli
-- runs_scored 139"), with the exact quote it rests on. Claims are
-- append-only. Evidence links other articles of the same event that report
-- the same subject and predicate, as SUPPORTS (same value) or REFUTES
-- (another value). Reviews are an append-only log; a claim is shown only
-- when its latest review approves it. Additive only.

CREATE TABLE claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id bigint NOT NULL REFERENCES articles (id),
    -- the article's event when the claim was extracted
    event_id bigint REFERENCES news_events (id),
    subject varchar(200) NOT NULL,
    subject_normalized varchar(200) NOT NULL,
    -- innings_score | all_out_for | chased | set_target | runs_scored
    -- | bowling_figures | won_by | lost_by
    predicate varchar(30) NOT NULL,
    value numeric NOT NULL,
    -- as written for comparison and display, e.g. 351/9, 6/75, 5 wickets
    value_text varchar(30) NOT NULL,
    unit varchar(20) NOT NULL,
    quote varchar(500) NOT NULL,
    -- character span of the quote in the title or description
    quote_start integer NOT NULL,
    quote_end integer NOT NULL,
    field varchar(15) NOT NULL,
    run_id bigint REFERENCES extraction_runs (id),
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_claims UNIQUE (article_id, subject_normalized, predicate, value_text, field)
);

CREATE INDEX idx_claims_event_id ON claims (event_id);

CREATE TABLE claim_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id bigint NOT NULL REFERENCES claims (id),
    article_id bigint NOT NULL REFERENCES articles (id),
    -- SUPPORTS | REFUTES (FEVER labels)
    label varchar(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_claim_evidence UNIQUE (claim_id, article_id)
);

CREATE TABLE claim_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id bigint NOT NULL REFERENCES claims (id),
    -- approved | rejected
    decision varchar(10) NOT NULL,
    reviewer varchar(255) NOT NULL,
    note varchar(500),
    created_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

CREATE INDEX idx_claim_reviews_claim_id ON claim_reviews (claim_id);
