--
-- PostgreSQL database dump
--

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    category character varying(50),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    embedding public.vector(384),
    entities text,
    keywords text,
    location character varying(255),
    published_at timestamp(6) without time zone,
    sentiment character varying(30),
    source character varying(255) NOT NULL,
    summary text,
    title character varying(500) NOT NULL,
    url text NOT NULL,
    news_event_id bigint,
    processed boolean NOT NULL
);


--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fact_checks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fact_checks (
    id bigint NOT NULL,
    agency character varying(255),
    claim text,
    explanation text,
    source_url character varying(255),
    verdict character varying(30),
    news_event_id bigint
);


--
-- Name: fact_checks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fact_checks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fact_checks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_events (
    id bigint NOT NULL,
    bias_analysis text,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    disagreement_level character varying(30),
    misinformation_risk double precision,
    summary text,
    title character varying(255) NOT NULL,
    verification_status character varying(30)
);


--
-- Name: news_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_sources (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    enabled boolean NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(20) NOT NULL,
    url text NOT NULL,
    CONSTRAINT news_sources_type_check CHECK (((type)::text = ANY ((ARRAY['RSS'::character varying, 'API'::character varying, 'WEBSITE'::character varying])::text[])))
);


--
-- Name: news_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: fact_checks fact_checks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fact_checks
    ADD CONSTRAINT fact_checks_pkey PRIMARY KEY (id);


--
-- Name: news_events news_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_events
    ADD CONSTRAINT news_events_pkey PRIMARY KEY (id);


--
-- Name: news_sources news_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_sources
    ADD CONSTRAINT news_sources_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: news_sources uk_news_source_url; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_sources
    ADD CONSTRAINT uk_news_source_url UNIQUE (url);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_article_published_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_published_at ON public.articles USING btree (published_at);


--
-- Name: idx_article_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_source ON public.articles USING btree (source);


--
-- Name: idx_articles_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_articles_embedding_hnsw ON public.articles USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: idx_articles_url_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_articles_url_unique ON public.articles USING btree (url);


--
-- Name: fact_checks fk4tu0wssop70ulecfvtl2agbq2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fact_checks
    ADD CONSTRAINT fk4tu0wssop70ulecfvtl2agbq2 FOREIGN KEY (news_event_id) REFERENCES public.news_events(id);


--
-- Name: articles fkiw0afn1minb7br63whgi251j8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT fkiw0afn1minb7br63whgi251j8 FOREIGN KEY (news_event_id) REFERENCES public.news_events(id);


--
-- PostgreSQL database dump complete
--

