-- X-NEWS V4 approach 1, stage 1b: every event-match decision made while the
-- v2 matcher runs (shadow or live) is stored with its probability, features
-- and model version, so v1 and v2 can be compared on real traffic and each
-- grouping traces back to the evidence behind it (information-layer spec
-- section 4 and 7). Additive only.

CREATE TABLE event_match_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id bigint NOT NULL REFERENCES articles (id),
    -- v1 | v2
    matcher varchar(10) NOT NULL,
    -- shadow | live
    mode varchar(10) NOT NULL,
    model_version varchar(100),
    -- null = a new event; no foreign key, so a later event merge can't be
    -- blocked by history rows
    chosen_event_id bigint,
    applied boolean NOT NULL,
    -- best candidate's probability; null when there were no candidates
    probability double precision,
    -- null when the v2 call failed
    threshold double precision,
    -- top candidates with probability (and, for v2, the feature values)
    candidates jsonb,
    latency_ms integer,
    -- set when the v2 call failed and v1 decided instead
    error varchar(500),
    created_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

CREATE INDEX idx_event_match_decisions_article_id
    ON event_match_decisions (article_id);

-- The v2 member queries filter articles by event; Postgres doesn't index
-- foreign keys automatically.
CREATE INDEX IF NOT EXISTS idx_articles_news_event_id
    ON articles (news_event_id);
