-- X-NEWS V4 roadmap step 1: provenance by default. Every generated output
-- (an event summary, an event-match decision, later extractions) points at
-- the run configuration that produced it: what kind of step, which model,
-- which prompt version and which code version. One row per distinct
-- configuration. Additive only.

CREATE TABLE extraction_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- e.g. event-analysis, event-matcher
    kind varchar(40) NOT NULL,
    -- e.g. gemini-3.6-flash, v1-centroid@0.94, v2-b-notemporal-.../<vocabulary>
    model varchar(150) NOT NULL,
    -- 'n/a' when the step has no prompt
    prompt_version varchar(40) NOT NULL,
    -- deployed image tag (sha-xxxxxxx), 'local' for a developer run
    code_version varchar(40) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_extraction_runs_config UNIQUE (kind, model, prompt_version, code_version)
);

ALTER TABLE news_events
    ADD COLUMN summary_run_id bigint REFERENCES extraction_runs (id);

ALTER TABLE event_match_decisions
    ADD COLUMN run_id bigint REFERENCES extraction_runs (id);
