-- X-NEWS V4 roadmap step 3: entities (people, places, organisations,
-- teams) as first-class records. Articles mention entities; aliases map the
-- many spellings to one entity. (Linking to Wikidata is left for a later,
-- separately designed migration.) Additive only.

CREATE TABLE entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name varchar(200) NOT NULL,
    -- team | name (person, place or organisation; the rules can't tell which)
    type varchar(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

CREATE TABLE entity_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id bigint NOT NULL REFERENCES entities (id),
    -- normalised spelling (lower case, letters/digits/&, single spaces)
    alias varchar(200) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_entity_aliases_alias UNIQUE (alias)
);

CREATE INDEX idx_entity_aliases_entity_id ON entity_aliases (entity_id);

CREATE TABLE entity_mentions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id bigint NOT NULL REFERENCES articles (id),
    entity_id bigint NOT NULL REFERENCES entities (id),
    -- the text as written in the article
    surface varchar(200) NOT NULL,
    -- title | description
    field varchar(15) NOT NULL,
    run_id bigint REFERENCES extraction_runs (id),
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_entity_mentions UNIQUE (article_id, entity_id, field)
);

CREATE INDEX idx_entity_mentions_entity_id ON entity_mentions (entity_id);
CREATE INDEX idx_entity_mentions_article_id ON entity_mentions (article_id);
